### ISSUE TITLE
Button click not detected on screens

### ISSUE THREAD

**Issue by Nagispace** [DimitarBogdanov/CommonUI#2]
Buttons works fine on the computer but not when the UI is displayed on attached monitor

**Comment by DimitarBogdanov** [comment]
Hello! I kind of abandoned this project. I started rewriting it a while ago, I can push the new version amd add a tutorial if that's fine by you.

**Comment by Nagispace** [comment]
yeah, I never really used lua but if the code if somewhat documented I should be able to pull something off

**Comment by DimitarBogdanov** [comment]
I'm going home right now, you can expect it to be uploaded and documented in the next 3-4 hrs

**Comment by RubberDuckShobe** [comment]
Looking forward to it, thank you for your work

**Comment by Nagispace** [comment]
Any update on the new code ?

**Comment by DimitarBogdanov** [comment]
Hey, sorry for the delay. I'll document now and push.

**Comment by DimitarBogdanov** [comment]
Alright fellas, it's up. It's changed a bit: now you need the additional DefaultControls module. This entire system is rewritten from the ground up to be extensible and stable. You don't have 15 arguments for CommonUI.NewButton(), now, you call it without arguments in the default controls module. DCM provides a set of controls that you can use. You don't have to, but it includes common stuff such as simple text boxes, buttons, boxes, headers, etc.

This is how you initialize CommonUI + DCM:
```lua
local CommonUI = require("common_ui").New()
local DefaultControls = require("default_controls").New(CommonUI)
```
Obviously you'd need to get the proper file path to `common_ui` and `default_controls` in the require calls.

You can now make a button as such:
```lua
local button = DefaultControls:BigButton()
button.PosX = 2
button.PosY = 13
button.SizeX = 6
button.SizeY = 1
button.Text = "End!"
button.Colour = colors.blue
button.TextColour = colors.white
button.DrawPriority = 2
button.OnClick = function()
    CommonUI:EndEventLoop()
    CommonUI:ClearScreen()
end

CommonUI:AddComponent(button)
CommonUI:BeginEventLoop()
```

_**TAKE NOTICE OF WHERE FUNCTIONS ARE CALLED WITH `:` AND WITH A DOT**_
[Explanation](https://stackoverflow.com/q/4911186/13580938)

This is a lot more writing than before, but it's worth it. Explanations:
- PosX, PosY, SizeX, SizeY - obvious what they do
- Text - what the button says
- Colour - the background colour of the button. The reason for the naming is because `Button` inherits `Box`, and this property is actually a property of `Box`
- TextColour - obvious
- DrawPriority - this is useful if you have e.g. a header and a button over it. You give the button a higher draw priority and not only will you ENSURE that it'll draw on top, you'll also make sure that it gets clicks properly (only the topmost component gets mouse click events)
- OnClick - called when the button is clicked
- AddComponent - adds the button to the internal list
- BeginEventLoop - starts listening for events such as mouse clicks

Reply with any questions you have and I'll answer. Closing for now.
